### PR TITLE
Update for OpenVINO support (and latest master from upstream)

### PR DESCRIPTION
**Pull request by kunaltyagi**
gen2_ros

### CODE REVIEW

**Comment by ardiya** [comment]
merge target to the gen2_ros instead of master?

**Comment by ardiya** [comment]
tested all images working

however running stereo sibpixel with NN at same time now causes runtime error instead of warning
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  , LRT: 'Stereo subpixel/extended mode is not stable when one of the following nodes are enabled: 'NeuralNetwork, ImageManip''
```

**Comment by kunaltyagi** [comment]
Can't do anything on that. Which line in particular does it throw in? Maybe I can disable that.

**Comment by ardiya** [comment]
it's not in the code or not searchable

**Comment by kunaltyagi** [comment]
Did you try gdb?

**Review by ardiya — APPROVED** [review]

**Pull request merged**
