### PR TITLE
Update to `depthai-core` submodule to latest multi_cam_support

### PR DESCRIPTION
**Pull request by ardiya**
update submodule and fix compile error since this->getConnection() is now `std::unique_ptr` instead of `std::shared_ptr`.

### CODE REVIEW

**Comment by ardiya** [comment]
Can be compiled but, I received runtime error
```
terminate called after throwing an instance of 'msgpack::v1::type_error'
  what():  std::bad_cast
Stack trace (most recent call last) in thread 149600:
#12   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#11   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f8425ce5292, in clone
#10   Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f8426bff608, in 
#9    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f8425ea6de3, in 
#8    Object "/home/ardiya/new_depthai_ws/devel/lib/depthai_ros_driver/gen2_ros_driver", at 0x5571e42b4bfb, in 
#7    Object "/home/ardiya/new_depthai_ws/devel/lib/depthai_ros_driver/gen2_ros_driver", at 0x5571e42b47e9, in 
#6    Object "/home/ardiya/new_depthai_ws/devel/lib/depthai_ros_driver/gen2_ros_driver", at 0x5571e429a360, in 
#5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f8425e7a6a8, in __cxa_throw
#4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f8425e7a3f6, in std::terminate()
#3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f8425e7a38b, in 
#2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f8425e6e910, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f8425be8858, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f8425c0918b, in gsignal
Aborted (Signal sent by tkill() 149463 1000)
```

seems like there's something wrong with the msgpack, need @kunaltyagi or @kota-rr help

**Comment by kota-rr** [comment]
`conn.get()` instead of `std::move`?
I have met `msgpack::v1::type_error` a lot, but I don't remember how I solved it. at which line is the `runtime` error occurring?

**Comment by ardiya** [comment]
I was just following Luxonis's DataQueue.cpp https://github.com/luxonis/depthai-core/blob/multi_cam_support/src/device/DataQueue.cpp#L29
let me try

**Comment by ardiya** [comment]
conn.get() doesn't compile.

**Comment by ardiya** [comment]
> at which line is the runtime error occurring?

@kota-rr 
Frame 13
```
┌──.../depthai_ros/depthai_ros_driver/include/depthai_ros_driver/device_ros.hpp┐
│   209                         msgpack::object_handle oh =                    │
│   210                                 msgpack::unpack(reinterpret_cast<const │
│   211                         msgpack::object obj = oh.get();                │
│   212                                                                        │
│   213                         MsgType msg;                                   │
│  >214                         obj.convert(msg);                              │
│   215                         msg.data = reader.bufferData();                │
│   216                                                                        │
│   217                         // publish data                                │
│   218                         publish(pub, msg, name);                       │
│   219                     }                                                  │
│   220                                                                        │
│   221                     guard.disable();                                   │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: rr::DeviceROS::gen* L214  PC: 0x55555557fac4 
(gdb) down
#13 rr::DeviceROS::generate_pub_lambda<depthai_datatype_msgs::RawImgFrame_<std::
allocator<void> > >(ros::NodeHandle&, std::__cxx11::basic_string<char, std::char
_traits<char>, std::allocator<char> >, unsigned long)::{lambda()#1}::operator()(
) const (this=0x7fffffffc960)
    at /home/ardiya/new_depthai_ws/src/depthai_ros/depthai_ros_driver/include/de
pthai_ros_driver/device_ros.hpp:214
(gdb) 
```

print obj
```
{<msgpack::v1::object> = {type = msgpack::v1::type::STR, via = {
      boolean = 25, u64 = 93823560581145, i64 = 93823560581145,
      f64 = 4.6354998053648725e-310, array = {size = 25,
        ptr = 0x7fffac000bc8}, map = {size = 25, ptr = 0x7fffac000bc8}, str = {
        size = 25, ptr = 0x7fffac000bc8 "\a\271\b\026\201"}, bin = {size = 25,
        ptr = 0x7fffac000bc8 "\a\271\b\026\201"}, ext = {size = 25,
        ptr = 0x7fffac000bc8 "\a\271\b\026\201"}}}, <No data fields>}
```
print msg
```
{fb = {type = 0, width = 0, height = 0, stride = 0, bytesPP = 0,
    p1Offset = 0, p2Offset = 0, p3Offset = 0}, category = 0, instanceNum = 0,
  sequenceNum = 0, ts = {sec = 0, nsec = 0},
  data = std::vector of length 0, capacity 0}
```

frame 12
```
┌──...i_ws/src/depthai_ros/external/msgpack-c/include/msgpack/v2/object_fwd.hpp┐
│   55               * @tparam T The type of v.                                │
│   56               * @param v The value you want to get. `v` is output parame│
│   57               * @return The reference of `v`.                           │
│   58               */                                                        │
│   59              template <typename T>                                      │
│  >60              T& convert(T& v) const { return v1::object::convert(v); }  │
│   61                                                                         │
│   62              using v1::object::with_zone;                               │
│   63              implicit_type convert() const;                             │
│   64          };                                                             │
│   65                                                                         │
│   66          #if !defined(MSGPACK_USE_CPP03)                                │
│   67                                                                         │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: rr::DeviceROS::gen* L60   PC: 0x55555557fac4 
    at /home/ardiya/new_depthai_ws/src/depthai_ros/depthai_ros_driver/include/de
pthai_ros_driver/device_ros.hpp:214
(gdb) down
#12 msgpack::v2::object::convert<depthai_datatype_msgs::RawImgFrame_<std::alloca
tor<void> > > (v=..., this=0x7fffc4fadeb0)
    at /home/ardiya/new_depthai_ws/src/depthai_ros/external/msgpack-c/include/ms
gpack/v2/object_fwd.hpp:60
(gdb)
```
frame 11
```
┌──...pthai_ws/src/depthai_ros/external/msgpack-c/include/msgpack/v1/object.hpp┐
│   1068            !msgpack::is_array<T>::value && !msgpack::is_pointer<T>::va│
│   1069            T&                                                         │
│   1070        >::type                                                        │
│   1071        object::convert(T& v) const                                    │
│   1072        {                                                              │
│  >1073            msgpack::operator>>(*this, v);                             │
│   1074            return v;                                                  │
│   1075        }                                                              │
│   1076                                                                       │
│   1077        template <typename T, std::size_t N>                           │
│   1078        inline T(&object::convert(T(&v)[N]) const)[N]                  │
│   1079        {                                                              │
│   1080            msgpack::operator>>(*this, v);                             │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: rr::DeviceROS::gen* L1073 PC: 0x55555557fac4 
gpack/v2/object_fwd.hpp:60
(gdb) down
#11 msgpack::v1::object::convert<depthai_datatype_msgs::RawImgFrame_<std::alloca
tor<void> > > (v=..., this=0x7fffc4fadeb0)
    at /home/ardiya/new_depthai_ws/src/depthai_ros/external/msgpack-c/include/ms
gpack/v1/object.hpp:1073
(gdb)
```

frame 10
```
┌──...epthai_ros/external/msgpack-c/include/msgpack/v1/adaptor/adaptor_base.hpp┐
│   53          typename msgpack::enable_if<                                   │
│   54              !is_array<T>::value,                                       │
│   55              msgpack::object const&                                     │
│   56          >::type                                                        │
│   57          operator>> (msgpack::object const& o, T& v) {                  │
│  >58              return msgpack::adaptor::convert<T>()(o, v);               │
│   59          }                                                              │
│   60          template <typename T, std::size_t N>                           │
│   61          inline                                                         │
│   62          msgpack::object const& operator>> (msgpack::object const& o, T(│
│   63              return msgpack::adaptor::convert<T[N]>()(o, v);            │
│   64          }                                                              │
│   65                                                                         │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: rr::DeviceROS::gen* L58   PC: 0x55555557fac4 
gpack/v1/object.hpp:1073
(gdb) Quit
(gdb) down
#10 msgpack::v1::operator>><depthai_datatype_msgs::RawImgFrame_<std::allocator<v
oid> > > (v=..., o=...)
    at /home/ardiya/new_depthai_ws/src/depthai_ros/external/msgpack-c/include/ms
gpack/v1/adaptor/adaptor_base.hpp:58
(gdb)
```
frame 9
```
──...pthai_ws/src/depthai_ros/external/msgpack-c/include/msgpack/v1/object.hpp┐
│   637         // Adaptor functors' member functions definitions.             │
│   638         template <typename T, typename Enabler>                        │
│   639         inline                                                         │
│   640         msgpack::object const&                                         │
│   641         adaptor::convert<T, Enabler>::operator()(msgpack::object const&│
│  >642             v.msgpack_unpack(o.convert());                             │
│   643             return o;                                                  │
│   644         }                                                              │
│   645                                                                        │
│   646         template <typename T, typename Enabler>                        │
│   647         template <typename Stream>                                     │
│   648         inline                                                         │
│   649         msgpack::packer<Stream>&                                       │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: rr::DeviceROS::gen* L642  PC: 0x55555557fac4 
    at /home/ardiya/new_depthai_ws/src/depthai_ros/external/msgpack-c/include/ms
gpack/v1/adaptor/adaptor_base.hpp:58
(gdb) down
#9  msgpack::v1::adaptor::convert<depthai_datatype_msgs::RawImgFrame_<std::alloc
ator<void> >, void>::operator() (this=<optimized out>, v=..., o=...)
    at /home/ardiya/new_depthai_ws/src/depthai_ros/external/msgpack-c/include/ms
gpack/v1/object.hpp:642
(gdb)
```

frame 8
```
┌──/usr/include/c++/9/tuple────────────────────────────────────────────────────┐
│   120             struct _Head_base<_Idx, _Head, false>                      │
│   121             {                                                          │
│   122               constexpr _Head_base()                                   │
│   123               : _M_head_impl() { }                                     │
│   124                                                                        │
│  >125               constexpr _Head_base(const _Head& __h)                   │
│   126               : _M_head_impl(__h) { }                                  │
│   127                                                                        │
│   128               constexpr _Head_base(const _Head_base&) = default;       │
│   129               constexpr _Head_base(_Head_base&&) = default;            │
│   130                                                                        │
│   131               template<typename _UHead>                                │
│   132                 constexpr _Head_base(_UHead&& __h)                     │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: rr::DeviceROS::gen* L125  PC: 0x55555557fac4 
ator<void> >, void>::operator() (this=<optimized out>, v=..., o=...)
    at /home/ardiya/new_depthai_ws/src/depthai_ros/external/msgpack-c/include/ms
gpack/v1/object.hpp:642
(gdb) down
#8  0x000055555557fac4 in depthai_datatype_msgs::RawImgFrame_<std::allocator<voi
d> >::msgpack_unpack (msgpack_o=..., this=0x7fffc4fadf80)
    at /usr/include/c++/9/tuple:125
(gdb)
```

frame 7
```
┌──/usr/include/c++/9/ext/new_allocator.h──────────────────────────────────────┐
│   84                                                                         │
│   85                template<typename _Tp1>                                  │
│   86                  _GLIBCXX20_CONSTEXPR                                   │
│   87                  new_allocator(const new_allocator<_Tp1>&) _GLIBCXX_USE_│
│   88                                                                         │
│  >89                ~new_allocator() _GLIBCXX_USE_NOEXCEPT { }               │
│   90                                                                         │
│   91                pointer                                                  │
│   92                address(reference __x) const _GLIBCXX_NOEXCEPT           │
│   93                { return std::__addressof(__x); }                        │
│   94                                                                         │
│   95                const_pointer                                            │
│   96                address(const_reference __x) const _GLIBCXX_NOEXCEPT     │
└──────────────────────────────────────────────────────────────────────────────┘
multi-thre Thread 0x7fffc4faf7 In: msgpack::v1::type:* L89   PC: 0x55555557f652 
    at /usr/include/c++/9/tuple:125
(gdb) down
#7  0x000055555557f652 in msgpack::v1::type::define_map<char const [3], depthai_
datatype_msgs::RawImgFrameSpecs_<std::allocator<void> >, char const [9], unsigne
d int, char const [12], unsigned int, char const [12], int, char const [3], dept
hai_common_msgs::Timestamp_<std::allocator<void> > >::msgpack_unpack (
    this=0x7fffc4fadf30, o=...) at /usr/include/c++/9/ext/new_allocator.h:89
(gdb) 
```

**Comment by kota-rr** [comment]
data struct seems not have changed. Something related to this ?
https://github.com/luxonis/depthai-core/commit/f092c10c870c96e62fea12f27adaca057a8cb934#diff-0487093b6a305321f0f1e0115a661f8f5b96a8c366ebfc4d970970c41905a829

**Pull request closed without merging**
